### PR TITLE
New date field

### PR DESCRIPTION
**Pull request by mattheu**
Dates are a little bit messy at the moment.
1. We have 4 different classes to handle this. Seems like a lot of repeated code.
2. The dates are stored without accounting for timezone. Dates should really be stored as UTC.
3. Any fix will probably break backwards compatability.

Propsed fix.
- We should have 1 date field class, and the format stored should be an argument.
- We should allow the option to convert to GMT on save. This should be true by default. 
- We can hack backwards compatability by filtering the fields and updating them with the new arguments so they match the old functionality exactly.

Concerns
- I don't really like this backwards compatability support - but I can't think of a better way.
- Timezones - I'm simply offsetting by `current_time` local minus `current_time` gmt. I think this is sufficient.

### CODE REVIEW

**Comment by mattheu** [comment]
@joehoyle would you be able to give me your thoughts on this? I think the wrapper I added is enough to handle backwards compatability.

**Comment by mattheu** [comment]
Tests are failing because PHP 5.2 got removed... But I hear its comming back?

**Comment by mattheu** [comment]
> Tests are failing because PHP 5.2 got removed... But I hear its comming back?

Ha... no tests were failing because I was causing a fatal error on 5.2 :smile:

**Comment by joehoyle** [comment]
@mattheu I think this is cool - like how you have implemented the backwards compat stuff.

**Comment by mattheu** [comment]
I'd like to write some tests to make sure this is all good.

* Ensure the backwards compatability stuff works OK.
* Ensure timezones works OK.
* How much flexibility can we realistically offer in terms of stored format

**Comment by mikeselander** [comment]
This branch is quite stale so I'm going to close it out for now.

**Pull request closed without merging**
