### PR TITLE
Check repeatable value exists

### PR DESCRIPTION
**Pull request by tomaszbakula**
If the value isn't set php will return a notice:

```
Undefined index: repeatable
```

### CODE REVIEW

**Comment by duablellc** [comment]
+1 To get this merged.  Notices are flooding our admin screens.

**Comment by mattheu** [comment]
Looks good. Thanks

**Comment by swissspidy** [comment]
Pretty sure this is wrong.

If I set `$field['repeatable']` to true, `! empty( $field['repeatable'] )` will return true. That means `get_post_meta()` will only return a single value despite this being a repeatable field.

**Comment by tomaszbakula** [comment]
Yes, I think you're right.

**Pull request merged**
