### PR TITLE
Fix check repeatable value exists

### LINKED ISSUE #348: Change from d5de34e to 0ff7b17 breaking repeatable fields when used in a plugin admin page
I did not test if it breaks when used inside of a theme, but when I included the recent changes into a plugin the repeatable field would always appear blank and after saving any added or removed fields disappeared and the initial blank field would reappear.

### PR DESCRIPTION
**Pull request by barryceelen**
- Checks if `$fields['repeatable']` is set.
  - If it is set, return the inverted value (as passing `false` to `get_post_meta()` means return all values and `true` means return a single value).
  - If `$fields['repeatable']` is empty, return `true` as we’d want to get a single meta value.

This should do the trick. (And apologies for not paying more attention here #338).

Fixes #348, #349, #344

### CODE REVIEW

**Comment by swissspidy** [comment]
Looks better, though I'd probably simply use `$single = ( ! isset( $field['repeatable'] ) || false === $field['repeatable'] )`.

**Comment by barryceelen** [comment]
@swissspidy Thanks, nicer indeed.

**Comment by tomaszbakula** [comment]
Did you test this code? I'm sure that your solution is wrong. There shouldn't be any condition. Third parameter in the `get_post_meta()` should be always equal false so this line should look like that `$values = (array) get_post_meta( $post_id, $field['id'] );`. I've tested this and it is the only solution which works for repeatable, non repeatable and grouped fields as well.

**Comment by swissspidy** [comment]
@tomaszbakula That came to my mind yesterday as well. `get_post_meta()` always returns an array when `$single = false`. Since the result is cast to an array anyway, this indeed shouldn't matter. If there were just some tests to prove it 🙂

**Comment by tomaszbakula** [comment]
I've tried to break it when `$single = false` but without success so it's probably correct solution :)

**Comment by barryceelen** [comment]
@tomaszbakula The context of these changes is that if multiple values existed for a particular meta key, the plugin displayed multiple fields even if `repeatable` was set to `false`. This was caused by the fact that the `$single` parameter of `get_post_meta()` was always set to `false`, making it retrieve all values.

Setting `$single` to `true` if `repeatable` is `false` (or if it is not set at all) makes `get_post_meta()` retrieve only a single value, even if multiple exist. Since an array is expected in the end, it is casting the result to an array. If we’re retrieving multiple values, `get_post_meta` already returns an array. Casting that to an array has no effect, as it already is one.

**Comment by tomaszbakula** [comment]
Ok. It makes sense. I wasn't aware of this issue. 
```
	public function init_fields( $post_id = 0 ) {

		foreach ( $this->_meta_box['fields'] as $key => $field ) {

			$values = array();

			$args = $field;
			unset( $args['id'] );
			unset( $args['type'] );
			unset( $args['name'] );

			$class = _cmb_field_class_for_type( $field['type'] );
			$single = empty( $field['repeatable'] );

			// If we are on a post edit screen - get metadata value of the field for this post
			if ( $post_id ) {
				$values = (array) get_post_meta( $post_id, $field['id'], $single );
			}

			if ( 'group' === $field['type'] && $single ) {
				$values = array( $values );
			}

			if ( class_exists( $class ) ) {
				$this->fields[] = new $class( $field['id'], $field['name'], (array) $values, $args );
			}

		}

	}
```

What do you think about this. I've added `if` statement which check if field is non repeatable and grouped and if the condition is met it adds additional array nesting for that field. It allows to keep the original grouped field structure.
I'm not sure if it's the best place for that statement but it seems to work fine.

**Comment by mikeselander** [comment]
This looks to me to address the issue - I've tested locally within group fields and default fields. I will add unit tests for this once it's on `develop` in our repo.

**Pull request merged**
