### PR TITLE
Readme main screenshot

### PR DESCRIPTION
**Pull request by ajitbohra**
- Main screenshot updated in readme.md
- Code for the same added to example-function.php so we can quickly
  change screenshots using the same

human-made-main-2

### CODE REVIEW

**Comment by mikeselander** [comment]
Hi @ajitbohra thanks for working on this! I like the updated screenshot, it looks really nice. I see a whole lot of other changes though, including changing the default `CMB_URL`. If we can get rid of all the code changes and just have the screenshot we can change this out 👍

**Comment by ajitbohra** [comment]
@mikeselander sure CMB_URL changed that as on windows path create issue will revert that.

Also under example-functions.php have added the field array for what we see in screenshot do you want me to remove that also ?

Let me know will make the changes.

**Comment by mikeselander** [comment]
@ajitbohra yes, please get rid of all of the code changes. I understand that it would make re-creating this a little easier but that file is supposed to only be for example functions and I'd rather not add more weight than necessary to it.

**Comment by ajitbohra** [comment]
@mikeselander as suggested have reverted code changes.

**Pull request merged**
